### ISSUE TITLE
How can I get rendering images without color? As I only want get the geometry of objects?

### ISSUE THREAD

**Issue by kszpxxzmc** [ashawkey/kiuikit#10]
As above.

**Comment by ashawkey** [comment]
@kszpxxzmc Hi, do you mean rendering depth/normal? just use the `--mode` option.

**Comment by kszpxxzmc** [comment]
Not normal, just assume objects are totally white, i.e. without textures.

**Comment by ashawkey** [comment]
In that case you'll have to do some lighting, otherwise the model will look all white. You'll have to modify the mesh loading code to achieve this, but I still recommend using normal rendering, which gives more information on geometry.
