### ISSUE TITLE
Regarding Blender Rendering

### ISSUE THREAD

**Issue by Yifehuang97** [ashawkey/kiuikit#11]
Thank you for your excellent work!
I have a few questions regarding PBR rendering in Blender.

**(1) Reliability of Metallic Roughness:**
Is the metallic roughness data reliable? For some GLB objects, it seems the material properties are given default values for metallicFactor and roughnessFactor. For example:
{
    'baseColorFactor': array([ 94,  94,  94, 255], dtype=uint8),
    'metallicFactor': 0.0,
    'roughnessFactor': 0.0,
    'doubleSided': True,
    'name': 'material_71'
}
I want to know if all metallic roughness values are reliable. If not, is there a way to verify the correctness of the rendered normal, metallic roughness (mr), and albedo maps?

**(2) Rendering Issue:**
I've encountered the following issue when rendering:
![image](https://github.com/ashawkey/kiuikit/assets/89707220/4b801f73-0468-4e79-b4c5-11fbfb506ae9)
Despite this error, the rendered result appears correct. Can I safely ignore this error?

Thank you for your help!

**Comment by ashawkey** [comment]
@Yifehuang97 Hi, the PBR mode is only tested for meshes with `Principled BSDF` shading node. Maybe you can send me the mesh file for more testing, or paste some rendering results?

**Comment by Yifehuang97** [comment]
Thanks for your prompt reply!

I tested a subset of the Objaverse dataset, and the GLB files I tested are available in the following ZIP file:
[glbs.zip](https://github.com/ashawkey/kiuikit/files/15383644/glbs.zip)

To check the material attributes, I used the following code snippet. However, I'm not sure if this is the best approach:
```
mesh = trimesh.load(glb_path)
for geometry in mesh.geometry.values():
    try:
        material = geometry.visual.material
    except:
        continue
    print(material._data)
```
Is this the recommended method for checking material attributes, or is there a better way to do this?
Thank you!

**Comment by Yifehuang97** [comment]
Sorry to bother you again.

I think my question is more about whether there is a standard way to filter out the Objaverse objects that have valid PBR attributes. I am not sure if this is a silly question, as I am not familiar with GLB files and Blender rendering.

Sorry for the inconvenience, and thanks for your help!

Best regards,
Yifeng

**Comment by ashawkey** [comment]
Hi, it seems most of the glbs you provided do not have PBR materials. It can be checked in multiple ways:
* load in blender and check the shading panel.
* open with windows 3d viewer and check the material data.
* load with `kiui.mesh.Mesh` and check if it has `metallicRoughness`, but this only works for a single mesh.

An example for expected output:
![image](https://github.com/ashawkey/kiuikit/assets/25863658/46f1ee08-36ee-4c93-9695-c16e1589e158)

**Comment by Yifehuang97** [comment]
Thank you for your response, and sorry to bother you again!

(1) For some meshes without PBR material, it seems they can still render, but the albedo and MR maps are completely black, as shown below:
![image](https://github.com/ashawkey/kiuikit/assets/89707220/0ef228a4-d78c-4011-8ae3-2b1cb4eb6233)
So, for this kind of rendering result, can I assume they are invalid and filter them out?

(2) Another question is regarding the following issue when rendering:
![image](https://github.com/ashawkey/kiuikit/assets/89707220/d06f5820-f12e-473d-a005-f553c8c347c8)

It seems this error doesn't affect the correctness of the rendering result, so maybe I can simply ignore it?
Sorry to bother you multiple times, and thanks for your help!

**Comment by ashawkey** [comment]
1. Yes, you may add an assert [here](https://github.com/ashawkey/kiuikit/blob/main/kiui/cli/blender_render.py#L121) to filter if they have PBR.
2. I don't encounter this error, maybe you can add `--verbose` to see if there is more message.

**Comment by Yifehuang97** [comment]
Thank you for your reply!

1. I added a function to check the PBR validity before the `setup_rendering(args)`:
```
def check_pbr_valid(args):
    valid = True
    for mat in bpy.data.materials:
        mat.use_nodes = True  # assert
        mat_nodes = mat.node_tree.nodes
        if 'Principled BSDF' not in mat_nodes:
            valid = False
            break
        node_bsdf = mat_nodes['Principled BSDF']  # assert all these exist...
        if 'Base Color' not in node_bsdf.inputs or 'Metallic' not in node_bsdf.inputs or 'Roughness' not in node_bsdf.inputs:
            valid = False
            break
    return valid
```

2. The error seems to occur when trying to render multiple objects in a single script call:
```
objects = objaverse.load_objects(
        uids=subset_filtered_csv,
    )
    args.outdir = save_dir
    args.depth = True
    for k, v in objects.items():
        args.mesh = v
        main(args)
```
When I use a subprocess and render one object at a time, this error doesn't appear again.
Thank you so much for your help!
