### ISSUE TITLE
Regarding the Channels in Metallic Roughness Map in Blender Rendering

### ISSUE THREAD

**Issue by Yifehuang97** [ashawkey/kiuikit#12]
Hi,

Sorry for bothering you again. I just want to know if there is a corresponding relationship between the channels in the metallic roughness map(3 channels) and the metallic or roughness properties.

Thank you!

**Comment by ashawkey** [comment]
Hi, you may refer to the official specification: https://registry.khronos.org/glTF/specs/2.0/glTF-2.0.html
> The textures for metalness and roughness properties are packed together in a single texture called metallicRoughnessTexture. Its green channel contains roughness values and its blue channel contains metalness values. This texture MUST be encoded with linear transfer function and MAY use more than 8 bits per channel.

**Comment by Yifehuang97** [comment]
Thank you!
