### ISSUE TITLE
Coordinnate System of Rendered Normal

### ISSUE THREAD

**Issue by StarRealMan** [ashawkey/kiuikit#13]
First, thank you for your great work!
Recently, we used your _blender_render.py_ for normal rendering, but we find its coordinate system misaligned with the normal data we previous construct.
Do you have any ideas? (Color format different or anything else?)
Looking forward to your reply.
![normal](https://github.com/ashawkey/kiuikit/assets/32333352/a78f62b0-fd07-49a7-a28f-67cdb16e1dcc)
(row 1: normal rendered from kiuikit
row 2: normal rendered from our model)

**Comment by ashawkey** [comment]
Hi, are you using the latest code that saves .exr instead of .png for
normals? It seems blender will apply a default color transformation to png
range.

Dongyu Yan ***@***.***> 于 2024年7月1日周一 06:04写道：

**Comment by StarRealMan** [comment]
Thank you for the fast reply.
Unfortunately, we used a former version that saves _.png_ instead of _.exr_.

**Comment by StarRealMan** [comment]
We tried to use the newest rendering code that saves _.exr_ normal file and the results matched as below:
![exr](https://github.com/ashawkey/kiuikit/assets/32333352/3081210b-b02a-40a6-a515-2e7fa8d33406)
(don't mind the mismatch of the scale)
But the problem is that we have already rendered for about 2 weeks using the old rendering code. :(.
Do you have any ideas about how to transform the already rendered data right?
Thank you so much for helping us!

**Comment by ashawkey** [comment]
I guess the best way is to re-render them... The transformation is non-linear and is very hard to invert. You may be able to convert the correct normal to the transformed space using this codebase (https://github.com/MrLixm/AgXc/tree/main/python), but it's not a good solution after all.
Really sorry for the wrong code before.

**Comment by StarRealMan** [comment]
Thank you for your solution!
We decided to re-render the normals, I guess it will not take too long.
