### ISSUE TITLE
error when rendering mesh: RuntimeError: expected scalar type float but found long int

### ISSUE THREAD

**Issue by YuQiao0303** [ashawkey/kiuikit#14]
Hi, author. Thank you for developing this wonderful tool!
When running `python -m kiui.render temp/meshes/model.obj`, I met the following error:

```bash
python -m kiui.render temp/meshes/model.obj
[INFO] load obj mesh: use texture from: temp/meshes/texture.png
[INFO] load obj mesh: load texture: (4096, 4096, 3)
[INFO] load mesh, v: torch.Size([5124, 3]), f: torch.Size([10248, 3])
[INFO] load mesh, vn: torch.Size([5124, 3]), fn: torch.Size([10248, 3])
[INFO] load mesh, vt: torch.Size([5619, 2]), ft: torch.Size([10248, 3])
Traceback (most recent call last):
  File "/opt/conda/envs/get3d/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/conda/envs/get3d/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/opt/conda/envs/get3d/lib/python3.8/site-packages/kiui/render.py", line 472, in <module>
    main()
  File "/opt/conda/envs/get3d/lib/python3.8/site-packages/kiui/render.py", line 431, in main
    gui = GUI(opt)
  File "/opt/conda/envs/get3d/lib/python3.8/site-packages/kiui/render.py", line 83, in __init__
    self.step()
  File "/opt/conda/envs/get3d/lib/python3.8/site-packages/kiui/render.py", line 130, in step
    albedo = torch.where(rast[..., 3:] > 0, albedo, torch.tensor(0).to(albedo.device)) # remove background
RuntimeError: expected scalar type float but found long int

```
The mesh file I use is from:
https://app.gazebosim.org/GoogleResearch/fuel/models/Crosley_Alarm_Clock_Vintage_Metal

Could you please help? Thank you!!!

**Comment by ashawkey** [comment]
@YuQiao0303 Hi, thanks for your interest in using this package!
Could you confirm to use the latest version? I cannot reproduce this bug:
<img width="1383" alt="image" src="https://github.com/user-attachments/assets/4623f846-e937-4a9e-b41a-bc68370dfe83">

**Comment by YuQiao0303** [comment]
> @YuQiao0303 Hi, thanks for your interest in using this package! Could you confirm to use the latest version? I cannot reproduce this bug: <img alt="image" width="1383" src="https://private-user-images.githubusercontent.com/25863658/351440382-4623f846-e937-4a9e-b41a-bc68370dfe83.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE3OTAwOTMsIm5iZiI6MTcyMTc4OTc5MywicGF0aCI6Ii8yNTg2MzY1OC8zNTE0NDAzODItNDYyM2Y4NDYtZTkzNy00YTllLWI0MWEtYmM2ODM3MGRmZTgzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI0VDAyNTYzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcwNjE5ZGM3YjBkMGY0Yjg1ZmRmYWEzYzljODBmZGFiZjAyNzQ4MjNjYTI3ODk2NGUxOWZmZjE2NWYzZTUwNDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6cMzpLHohQP-I0fv-LnMyCbLzE1ZgmGQNnI13HwsN4s">

Thank you for your reply!!! 
Though I tried the latest version, it still raises the same error, but now I figured it out.

Simply replace the `torch.tensor(0)` in  kiui/render.py", line 130
```python
    albedo = torch.where(rast[..., 3:] > 0, albedo, torch.tensor(0).to(albedo.device)) # remove background
```
to `torch.tensor(0.0)`
```python
albedo = torch.where(rast[..., 3:] > 0, albedo, torch.tensor(0.0).to(albedo.device)) # remove background
```



Maybe it's related to pytorch version, which I currently use torch1.9.0+cu111.

Thank you so much!!!

**Comment by YuQiao0303** [comment]
> > @YuQiao0303 Hi, thanks for your interest in using this package! Could you confirm to use the latest version? I cannot reproduce this bug: <img alt="image" width="1383" src="https://private-user-images.githubusercontent.com/25863658/351440382-4623f846-e937-4a9e-b41a-bc68370dfe83.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE3OTAwOTMsIm5iZiI6MTcyMTc4OTc5MywicGF0aCI6Ii8yNTg2MzY1OC8zNTE0NDAzODItNDYyM2Y4NDYtZTkzNy00YTllLWI0MWEtYmM2ODM3MGRmZTgzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI0VDAyNTYzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcwNjE5ZGM3YjBkMGY0Yjg1ZmRmYWEzYzljODBmZGFiZjAyNzQ4MjNjYTI3ODk2NGUxOWZmZjE2NWYzZTUwNDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6cMzpLHohQP-I0fv-LnMyCbLzE1ZgmGQNnI13HwsN4s">
> 
> Thank you for your reply!!! Though I tried the latest version, it still raises the same error, but now I figured it out.
> 
> Simply replace the `torch.tensor(0)` in kiui/render.py", line 130
> 
> ```python
>     albedo = torch.where(rast[..., 3:] > 0, albedo, torch.tensor(0).to(albedo.device)) # remove background
> ```
> 
> to `torch.tensor(0.0)`
> 
> ```python
> albedo = torch.where(rast[..., 3:] > 0, albedo, torch.tensor(0.0).to(albedo.device)) # remove background
> ```
> 
> Maybe it's related to pytorch version, which I currently use torch1.9.0+cu111.
> 
> Thank you so much!!!


and also here: modify 1 to 1.0
normal_image = torch.where(rast[..., 3:] > 0, normal_image, torch.tensor(1.0).to(normal_image.device)) # remove background

**Comment by ashawkey** [comment]
Thanks! It's reasonable, I have fixed the code too.
