### ISSUE TITLE
Gridencode error due to  Microsoft Visual C++ installation

### ISSUE THREAD

**Issue by newzaungo3** [ashawkey/kiuikit#15]
Hello I have run LGM inference for mesh extraction but got error "RuntimeError: Could not locate a supported Microsoft Visual C++ installation" 

could you tell me about version of Microsoft Visual C++ that support it?

**Comment by ashawkey** [comment]
@newzaungo3 Hi, unfortunately Windows environment is quite complicated, you have to install correct MSVC version and CUDA version. You may check this: https://quasar.ugent.be/files/doc/cuda-msvc-compatibility.html

**Comment by ashawkey** [comment]
closed for now.
