### ISSUE TITLE
Difference in normal image with other method

### ISSUE THREAD

**Issue by KhanhNgoDuy** [ashawkey/kiuikit#18]
Hi, I'm using `kiuikit` to render normal images from 3D files (2nd image). But when I use other methods (3rd image) ([MiDaS](https://github.com/isl-org/MiDaS), [Omnidata](https://github.com/EPFL-VILAB/omnidata), [DSINE](https://github.com/baegwangbin/DSINE)), the estimated normal maps from them looks quite different in the main region of the image (excluding the background).

Is there a difference in the definition of the normal map rendered from kiuikit, and those from these methods?
If yes, do you have any suggestions so that the rendered normal image is in the same format as in the other methods?
Thank you!!

![rgb](https://github.com/user-attachments/assets/d7ffe8f5-b95b-4fb3-8f5d-196fb02b1d1e)
![kiuikit](https://github.com/user-attachments/assets/507cfe9e-674f-4152-966c-0e8621d7d2da)
![dsine](https://github.com/user-attachments/assets/136d255d-3151-4d63-ae59-14fa570dee31)

**Comment by ashawkey** [comment]
@KhanhNgoDuy Hi, which tool are you using, `kiui.cli.blender_render` or `kire`?
Normal image are visualization of the normal vectors, so it will be affected by the coordinate convention. You may try to switch RGB channels or invert the signal (assume in [-1, 1]) to match these two images.

**Comment by KhanhNgoDuy** [comment]
Hi, I'm based on [this script](https://github.com/ashawkey/kiuikit/blob/main/kiui/render.py#L437), with `--mode = normal` and `--force_cuda_rast` enabled

**Comment by ashawkey** [comment]
![image](https://github.com/user-attachments/assets/3314c341-326b-4ed6-bee3-55a96f1cac4a)
`kire` follows the OpenGL convention (https://kit.kiui.moe/camera/). It seems the normal in the second image has x/y axes direction inverted, you may try to negate them and compare.

**Comment by KhanhNgoDuy** [comment]
is there a convenient way to achieve this?

**Comment by ashawkey** [comment]
Unfortunately no automatic way. You can check the pixel value at the same location and compare them to see if it should be negated or switched with another axis.

**Comment by ashawkey** [comment]
closed for now.
