### ISSUE TITLE
How to change this camera to OpenCV format?

### ISSUE THREAD

**Issue by xiaobiaodu** [ashawkey/kiuikit#3]
Hi

Thanks for your excellent work. Could you please share how to change your GUI to adapt the OpenCV format? what params should be changed?

Thanks for your help in advance!

**Comment by ashawkey** [comment]
@echosum Hi, it may be a little complex to modify the GUI, as all the functions are assumed to be in OpenGL format. 
It would be easier to transform your camera poses into OpenGL format instead:
https://github.com/ashawkey/kiuikit/blob/main/kiui/cam.py#L50

**Comment by xiaobiaodu** [comment]
Hi 

Thanks for your reply! I am wondering how to transfer standard coordinates (x forward, y right, z up) with colmap (opencv) camera into the global opengl  and camera opengl coordinate system?

**Comment by ashawkey** [comment]
Usually I will:
(1) Convert the axes (you may refer to https://kit.kiui.moe/camera/) by switching and negating the **rows** of camera poses.
(2) In the correct world coordinate system, draw some example camera poses to see if it's opengl or opencv convention (by the forward direction), and negate the **cols** of camera poses.
