### ISSUE TITLE
Difference on the PBR rendering logic between kiuikit and nvdiffmodeling

### ISSUE THREAD

**Issue by FishWoWater** [ashawkey/kiuikit#5]
Hi! Thanks for your wonderful tool~

I have noticed that your pbr rendering logic (around Line https://github.com/ashawkey/kiuikit/blob/ea0c7006f5b6dc4e4a8dc8709021ec0d4cf10dde/kiui/render.py#L163) is different from the one in nvdiffmodeling (https://github.com/NVlabs/nvdiffmodeling/blob/9b2ba2eff83c7d90127f78c20773b06ddc3ae1db/src/renderutils/bsdf.py#L114)

How to understand the difference? When I use your implementation to render a chair with metallic legs, the color of chair legs seem to overflow (showing incorrect yellow color). I am wondering whether it's because of incorrect specular terms?  I have tried to normalize the image before conversion to 8-bit, but in that case the overall image intensity is flickering

Thank you very much

**Comment by ashawkey** [comment]
@FishWoWater Hi, I think they are the same? `spec_str` is just 0 in our setting.
Coud you give an example of the rendered image?

**Comment by FishWoWater** [comment]
OHHH  I get it, they are actually the same (just difference between point light and envlight)      

But the rendered video seems incorrect (no problem with gui model viewer)

`python -m kiui.render chair.obj --force_cuda_rast --pbr --mode pbr --wogui --save_video video.mp4`

<img width="762" alt="image" src="https://github.com/ashawkey/kiuikit/assets/37951601/a692ed9b-92a6-4c28-9bf7-1ccfde888421">

<img width="619" alt="image" src="https://github.com/ashawkey/kiuikit/assets/37951601/9be28a1b-cf90-45c2-9a9c-781f4dc18c1f">


https://github.com/ashawkey/kiuikit/assets/37951601/7e1e3bc3-5ecb-4cf7-bbde-f439aad1c71c

**Comment by ashawkey** [comment]
This looks strange... the rendering in gui mode and saved video should be the same. 
Since I cannot reproduce it, you may check the video saving part for debugging?

**Comment by FishWoWater** [comment]
Seems some strange problem with my headless server, it works with my windows PC for both offscreen or GUI rendering. 

Closing now, thanks~
