### ISSUE TITLE
Render image from arbitrary view in Python

### ISSUE THREAD

**Issue by KhanhNgoDuy** [ashawkey/kiuikit#9]
Hi, thank you for this awesome project. 

I have read the documentations on using `kire` to render image from a 3d file. However, the view can only be controlled via `num_azimuth` and `elevation`.

How can I render image from a 3d file, given any arbitrary viewing angle with Python?
Also, does `kiuikit` allow control over the distance from the camera to the object, so that I can zoom in and out to the object?

**Comment by ashawkey** [comment]
@KhanhNgoDuy Hi, thanks for your interest!
Sure, you'll need to modify the code a little for arbitrary view angles [here](https://github.com/ashawkey/kiuikit/blob/main/kiui/render.py#L437). You can use `--radius` (in CMD) or the mouse wheel (in GUI) for zooming.
